name: mTech
version: 0.1.2
main: api.bottleofench.main.Main
api-version: 1.18
authors: [ bottleofench ]

commands:
  mtech:
    aliases:
      - tech

permissions:
  mtech:
    default: op
    children:
      server-profile:
        default: op
      reload:
        default: op
      world:
        default: op
        children:
          world-profile:
            default: op
          gamerule:
            default: op
          difficulty:
            default: op
          pvp:
            default: op
          spawn-limit:
            default: op
            children:
              reset:
                default: op
              monsters:
                default: op
              animals:
                default: op
              ambient:
                default: op
              water-ambient:
                default: op
              water-animals:
                default: op
          ticks-per-mob-spawn:
            default: op
            children:
              reset:
                default: op
                monsters:
                  default: op
                animals:
                  default: op
                ambient:
                  default: op
                water-ambient:
                  default: op
                water-animals:
                  default: op