name: mTech
version: 0.2
main: api.bottleofench.main.Main
api-version: 1.18
authors: [ bottleofench ]

commands:
  mtech:
    aliases:
      - tech

permissions:
  mtech:
    default: op
    children:
      player:
        children:
          player-profile:
            description: Show player profile
      server-profile:
        description: Show server profile
      reload:
        description: Reload config
      world:
        children:
          world-profile:
            description: Show world profile
          gamerule:
            description: Set gamerule in specific world
          difficulty:
            description: Set difficulty in specific world
          pvp:
            description: Set pvp mode in specific world
          spawn-limit:
            children:
              reset:
                description: Reset spawn limits in specific world
              monsters:
                description: Set spawn limits for monsters in specific world
              animals:
                description: Set spawn limits for animals in specific world
              ambient:
                description: Set spawn limits for ambient mobs in specific world
              water-ambient:
                description: Set spawn limits for water ambient mobs in specific world
              water-animals:
                description: Set spawn limits for water animals in specific world
          ticks-per-mob-spawn:
            children:
              t-reset:
                description: Reset ticks per mob spawn in specific world
              t-monsters:
                description: Set ticks per mob spawn for monsters in specific world
              t-animals:
                description: Set ticks per mob spawn for animals in specific world
              t-ambient:
                description: Set ticks per mob spawn for ambient mobs in specific world
              t-water-ambient:
                description: Set ticks per mob spawn for water ambient mobs in specific world
              t-water-animals:
                description: Set ticks per mob spawn for water animals in specific world