name: mTech
version: 0.1.2
main: api.bottleofench.main.Main
api-version: 1.18
authors: [ bottleofench ]

commands:
  mtech:
    aliases:
      - tech

permissions:
  mtech:
    default: op
    children:
      player:
        children:
          player-profile:
            description: yes.
      server-profile:
        description: yes.
      reload:
        description: yes.
      world:
        children:
          world-profile:
            description: yes.
          gamerule:
            description: yes.
          difficulty:
            description: yes.
          pvp:
            description: yes.
          spawn-limit:
            children:
              reset:
                description: yes.
              monsters:
                description: yes.
              animals:
                description: yes.
              ambient:
                description: yes.
              water-ambient:
                description: yes.
              water-animals:
                description: yes.
          ticks-per-mob-spawn:
            children:
              t-reset:
                description: yes.
              t-monsters:
                description: yes.
              t-animals:
                description: yes.
              t-ambient:
                description: yes.
              t-water-ambient:
                description: yes.
              t-water-animals:
                description: yes.