name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Prepare to upload artifact
        run: mkdir staging && cp target/mTech-0.2.jar staging && mv staging/mTech-0.2.jar staging/mTech.jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mTech
          path: staging
